version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      HOSTNAME: localhost
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"