name: Build Node.js 

on:
  pull_request:
  push:
    branches:
    - refactoring

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: yarn
    - run: yarn build --if-present