name: Continuous Integration

on:
  pull_request:
  push:
    branches:
    - refactoring

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{js,md,ts,json}